# Variables that are defined globally for the pipeline
variables:
  PIPELINEVERSION: "2.1.0"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_STRATEGY: "clone"
  
  # Regulare expression pattern
  # enclose the branch name with ^ and $
  # separete severl branch names with |
  # e.g. /^main$|^main_1_0$/
  STABLE_BRANCHES: /^master$/
  
  # Name of the unstable branch (if it exists)
  # UNSTABLE_BRANCH: unstable_master

include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates-2-1.yml'

stages:
  - update
  - build
  - test
  - regressionTest
  - unstableBuild
  - unstableTest
  - deploy
  - codequality
  - package
  - badges

.win:
  tags: ["windows", "docker"]
  needs: []
  before_script:
    # activate compiler
    - '& $VCvarsall'
    # make cmake find qt
    - $env:CMAKE_PREFIX_PATH=$env:QT_INSTALL_PATH
  artifacts:
    paths:
      - build
      - install-msvc*

.linux:
  tags: ["linux", "docker"]
  needs: []
  before_script:
    # make cmake find qt
    - export CMAKE_PREFIX_PATH=$QT_INSTALL_PATH
  variables:
    GIT_SUBMODULE_STRATEGY: "none"
  artifacts:
    paths:
      - build
      - install-linux*

.win_20:
  extends:
    - .win
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-2_0-win
  variables:
    VCvarsall: $VCvarsall_515

.win_17:
  extends:
    - .win
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-1_7-win
  variables:
    VCvarsall: $VCvarsall_512

.linux_20:
  extends:
    - .linux
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-2_0-buster

.linux_17:
  extends:
    - .linux
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/gtlabdev-1_7-buster

# build on Windows system
windowsBuildDebug:
  stage: build
  extends: 
    - .win_17
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install-msvc2017-dbg -DBUILD_UNITTESTS=ON
    - cmake --build build --target install
    
windowsBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .win_20
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install-msvc2019-dbg -DBUILD_UNITTESTS=ON
    - cmake --build build --target install

windowsBuildRelease:
  stage: build
  extends: 
    - .win_17
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install-msvc2017
    - cmake --build build --target install

windowsBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .win_20
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install-msvc2019
    - cmake --build build --target install

# build on Linux system
linuxBuildDebug:
  stage: build
  extends: 
    - .linux_17
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install-linux-dbg -DBUILD_UNITTESTS=ON
    - cmake --build build --target install
    
linuxBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .linux_20
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install-linux-dbg -DBUILD_UNITTESTS=ON
    - cmake --build build --target install

linuxBuildRelease:
  stage: build
  extends: 
    - .linux_17
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install-linux
    - cmake --build build --target install
 
linuxBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .linux_20
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install-linux
    - cmake --build build --target install


# run tests using the binary built before
testWin:
  stage: test
  extends: 
    - .winTestTemplate
  needs: 
    - windowsBuildDebug
  dependencies: 
    - windowsBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

testWinUnstable:
  stage: unstableTest
  extends:
    - .winTestTemplate
  needs: 
    - windowsBuildDebugUnstable
  dependencies: 
    - windowsBuildDebugUnstable
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable  

testLinux:
  stage: test
  extends: 
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebug
  script:
    - export LD_LIBRARY_PATH=`pwd`/install-linux-dbg/lib/logging
    - ./build/GTlabLoggingTests --gtest_output=xml:unittests.xml
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable    

testLinuxUnstable:
  stage: unstableTest
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable 
    LINUX_QT_DIR: /opt/Qt/5.15.2/gcc_64
  extends: 
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugUnstable
  script:
    - export LD_LIBRARY_PATH=`pwd`/install-linux-dbg/lib/logging
    - ./build/GTlabLoggingTests --gtest_output=xml:unittests.xml

.package:
  stage: package
  tags: ["docker", "linux"]
  image: debian:buster
  script:
    - cp -r install-$toolchain-dbg/* install-$toolchain
    - mv install-$toolchain gtlab-logging-$toolchain
    - tar czf gtlab-logging-$toolchain.tar.gz gtlab-logging-$toolchain
  artifacts:
    name: "gtlab-logging-$toolchain"
    paths: ["gtlab-logging-$toolchain.tar.gz"]
  variables:
    toolchain: msvc2019
    GIT_STRATEGY: "none"

package-win-gtlab_2.0:
  extends: [".package"]
  needs: ["windowsBuildDebugUnstable", "windowsBuildReleaseUnstable"]
  variables:
    toolchain: msvc2019

package-win-gtlab_1.7:
  extends: [".package"]
  needs: ["windowsBuildDebug", "windowsBuildRelease"]
  variables:
    toolchain: msvc2017

package-linux-gtlab_2.0:
  extends: [".package"]
  needs: ["linuxBuildDebugUnstable", "linuxBuildReleaseUnstable"]
  variables:
    toolchain: linux

package-linux-gtlab_1.7:
  extends: [".package"]
  needs: ["linuxBuildDebug", "linuxBuildRelease"]
  variables:
    toolchain: linux

.conan:
  stage: package
  needs: []
  before_script:
    - pip install --upgrade conan==1.59.0 --quiet
    - conan profile new default --detect --force
  script:
    # Remove all local packages matching at-twk/unstable
    - conan remote add gitlab https://gitlab.dlr.de/api/v4/projects/20199/packages/conan --force
    - conan remove *$CONAN_CHANNEL_REFERENCE -f
    - conan create . $CONAN_CHANNEL_REFERENCE  -pr $CONAN_PROFILE -pr:b $CONAN_PROFILE
  variables:
    CONAN_LOGIN_USERNAME: ci_user
    CONAN_PASSWORD: ${CI_JOB_TOKEN}
    CONAN_CHANNEL_REFERENCE: at-twk/testing
    CONAN_PROFILE: default
    GIT_SUBMODULE_STRATEGY: "none"

conan-pkg-linux:
  extends:
    - .conan
  image: conanio/gcc8
  tags: ["docker", "linux"]
  before_script:
    - pip install --upgrade conan==1.59.0 --quiet
    - conan profile new default --detect --force
    - conan profile update settings.compiler.libcxx=libstdc++11 default
  after_script:
    # Upload all packages. This should only include the newly created ones
    - if [ $CI_COMMIT_TAG ]; then conan upload *$CONAN_CHANNEL_REFERENCE  --all -c -r gitlab; fi

conan-pkg-win:
  extends:
    - .conan
  image: at-twk-hal9000.intra.dlr.de:5000/dlr-at/msvc-2019
  tags: ["docker", "windows"]
  before_script:
    - $env:path += ";c:\Python3;c:\Python3\Scripts"
    - pip install --upgrade conan==1.59.0 --quiet
    - conan profile new default --detect --force
  after_script:
      # Upload all packages. This should only include the newly created ones
    - $env:path += ";c:\Python3;c:\Python3\Scripts"
    - if ($CI_COMMIT_TAG -ne $null) {conan upload *$CONAN_CHANNEL_REFERENCE  --all -c -r gitlab }

# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate
 
cppcheck:
  stage: codequality
  extends: .cppCheckReportTemplate
  allow_failure: true

pages:
  stage: badges
  extends: .pageTemplate

# badges
badges:
  stage: badges
  extends: 
    - .stable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebug
    - linuxBuildDebug
    - testWin
    - testLinux
    - codingstyle

badgesUnstable:
  stage: badges
  extends: 
    - .unstable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebugUnstable
    - linuxBuildDebugUnstable
    - testWinUnstable
    - testLinuxUnstable
    - codingstyle
