#################################################################
############### GTlab Standard Pipeline Version 2.0.0 ###########
#################################################################
# These variables are defined in the CI project settings:
#  CATEGORY: 02_core
#  PROFILENAME: logging.pro
#  TARGETDIRNAME: logging
#  TARGETNAME: GTlabLogging
#  UNITTESTSNAME: GTlabUnitTest

# These variables are defined in the AT-TWK group settings:
#   DEVTOOLS_Linux_Stable
#   DEVTOOLS_Linux_Unstable
#   DEVTOOLS_Win_Stable 
#   DEVTOOLS_Win_Unstable
#   WIN_PYTHON
#   STABLE_MAJOR
#   STABLE_MINOR
#   UNSTABLE_MAJOR
#   UNSTABLE_MINOR

# Variables that are defined globally for the pipeline
variables:
  PIPELINEVERSION: "2.0.0"
  GIT_SUBMODULE_STRATEGY: none
  
  # Regulare expression pattern
  # enclose the branch name with ^ and $
  # separete severl branch names with |
  # e.g. /^main$|^main_1_0$/
  STABLE_BRANCHES: /^master$/
  
  # Name of the unstable branch (if it exists)
  # UNSTABLE_BRANCH: unstable_master

include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates-2-0.yml'

stages:
  - update
  - build
  - test
  - regressionTest
  - unstableBuild
  - unstableTest
  - deploy
  - codequality
  - package
  - badges

# DevTools update
devtoolsUpdateWindows:
  stage: update
  extends: .devToolsUpdateWindows

devtoolsUpdateLinux:
  stage: update
  extends: .devToolsUpdateLinux

# build on Windows system
windowsBuildDebug:
  stage: build
  extends: 
    - .stable-debug
    - .buildWinDebug
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

windowsBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildWinDebug
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable

windowsBuildRelease:
  stage: build
  extends: 
    - .stable-release
    - .buildWinRelease
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

windowsBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildWinRelease
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable

# build on Linux system
linuxBuildDebug:
  stage: build
  extends: 
    - .stable-debug
    - .buildLinuxDebug
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable

linuxBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildLinuxDebug 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
 
linuxBuildRelease:
  stage: build
  extends: 
    - .stable-release
    - .buildLinuxRelease 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable

linuxBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildLinuxRelease 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable

# run tests using the binary built before
testWin512:
  stage: test
  extends: 
    - .stable-debug
    - .winTestTemplate
  needs: 
    - windowsBuildDebug
  dependencies: 
    - windowsBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

testWin512Unstable:
  stage: unstableTest
  extends:
    - .unstable-debug  
    - .winTestTemplate
  needs: 
    - windowsBuildDebugUnstable
  dependencies: 
    - windowsBuildDebugUnstable
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable  

testLinux512:
  stage: test
  extends: 
    - .stable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebug
  dependencies:
    - linuxBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable    

testLinux512Unstable:
  stage: unstableTest
  extends: 
    - .unstable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugUnstable
  dependencies:
    - linuxBuildDebugUnstable
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable   

# deployment
createJobs:
  stage: deploy
  extends:
    - .createJobsTemplate
  dependencies: []
  variables:
    WinReStableJob: windowsBuildRelease
    WinReUnstableJob: windowsBuildReleaseUnstable
    WinDeStableJob: windowsBuildDebug
    WinDeUnstableJob: windowsBuildDebugUnstable
    LinReStableJob: linuxBuildRelease
    LinReUnstableJob: linuxBuildReleaseUnstable
    LinDeStableJob: linuxBuildDebug
    LinDeUnstableJob: linuxBuildDebugUnstable

triggerJobs:
  stage: deploy
  extends: .only-tags
  needs:
    - createJobs
  trigger:
    include:
      - artifact: deploy.yml
        job: createJobs
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  
# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate
 
cppcheck:
  stage: codequality
  extends: .cppCheckTemplate

pages:
  stage: badges
  extends: .pageTemplate

package:
  stage: package
  extends: .packageTemplate

# badges
badges:
  stage: badges
  extends: 
    - .stable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebug
    - linuxBuildDebug
    - testWin512
    - testLinux512
    - codingstyle

badgesUnstable:
  stage: badges
  extends: 
    - .unstable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebugUnstable
    - linuxBuildDebugUnstable
    - testWin512Unstable
    - testLinux512Unstable
    - codingstyle
