#################################################################
############### GTlab Standard Pipeline Version 2.1.0 ###########
#################################################################
# These variables are defined in the CI project settings:
#  CATEGORY: 02_core
#  PROFILENAME: logging.pro
#  TARGETDIRNAME: logging
#  TARGETNAME: GTlabLogging
#  UNITTESTSNAME: GTlabUnitTest

# These variables are defined in the AT-TWK group settings:
#   DEVTOOLS_Linux_Stable
#   DEVTOOLS_Linux_Unstable
#   DEVTOOLS_Win_Stable 
#   DEVTOOLS_Win_Unstable
#   WIN_PYTHON
#   STABLE_MAJOR
#   STABLE_MINOR
#   UNSTABLE_MAJOR
#   UNSTABLE_MINOR

# Variables that are defined globally for the pipeline
variables:
  PIPELINEVERSION: "2.1.0"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_STRATEGY: "clone"
  
  # Regulare expression pattern
  # enclose the branch name with ^ and $
  # separete severl branch names with |
  # e.g. /^main$|^main_1_0$/
  STABLE_BRANCHES: /^master$/
  
  # Name of the unstable branch (if it exists)
  # UNSTABLE_BRANCH: unstable_master

include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates-2-1.yml'

stages:
  - update
  - build
  - test
  - regressionTest
  - unstableBuild
  - unstableTest
  - deploy
  - codequality
  - package
  - badges

# Tag pipeline jobs
findCodeBaseStatus:
  stage: .pre
  extends: 
    - .only-tags-parent
    - .findCodeBaseStatusTemplate
  tags:
    - Win10

triggerDeployment:
  stage: deploy
  extends: .only-tags-parent
  trigger:
    include: .gitlab-ci.yml
    forward:
      pipeline_variables: true
    strategy: depend
  variables:
    STABLE_BASE: $BUILD_STABLE_BASE

# DevTools update
devtoolsUpdateWindows:
  stage: update
  extends: .devToolsUpdateWindows

devtoolsUpdateLinux:
  stage: update
  extends: .devToolsUpdateLinux

# build on Windows system
windowsBuildDebug:
  stage: build
  extends: 
    - .stable-debug
    - .buildWinDebug
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable
    JOM_PATH: $JOM_PATH_512
    QMAKE_PATH: $QMAKE_PATH_512
    VCvarsall: $VCvarsall_512

windowsBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildWinDebug
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    JOM_PATH: $JOM_PATH_515
    QMAKE_PATH: $QMAKE_PATH_515
    VCvarsall: $VCvarsall_515

windowsBuildRelease:
  stage: build
  extends: 
    - .stable-release
    - .buildWinRelease
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable
    JOM_PATH: $JOM_PATH_512
    QMAKE_PATH: $QMAKE_PATH_512
    VCvarsall: $VCvarsall_512

windowsBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildWinRelease
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    JOM_PATH: $JOM_PATH_515
    QMAKE_PATH: $QMAKE_PATH_515
    VCvarsall: $VCvarsall_515
    
# build on Linux system
linuxBuildDebug:
  stage: build
  extends: 
    - .stable-debug
    - .buildLinuxDebug
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable
    QMAKE_EXECUTABLE: /opt/Qt/5.12.5/gcc_64/bin/qmake

linuxBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildLinuxDebug 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    QMAKE_EXECUTABLE: /opt/Qt/5.15.2/gcc_64/bin/qmake
 
linuxBuildRelease:
  stage: build
  extends: 
    - .stable-release
    - .buildLinuxRelease 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable
    QMAKE_EXECUTABLE: /opt/Qt/5.12.5/gcc_64/bin/qmake

linuxBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildLinuxRelease 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    QMAKE_EXECUTABLE: /opt/Qt/5.15.2/gcc_64/bin/qmake

# run tests using the binary built before
testWin:
  stage: test
  extends: 
    - .stable-debug
    - .winTestTemplate
  needs: 
    - windowsBuildDebug
  dependencies: 
    - windowsBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

testWinUnstable:
  stage: unstableTest
  extends:
    - .unstable-debug  
    - .winTestTemplate
  needs: 
    - windowsBuildDebugUnstable
  dependencies: 
    - windowsBuildDebugUnstable
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable  

testLinux:
  stage: test
  extends: 
    - .stable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebug
  dependencies:
    - linuxBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable    

testLinuxUnstable:
  stage: unstableTest
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable 
    LINUX_QT_DIR: /opt/Qt/5.15.2/gcc_64
  extends: 
    - .unstable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugUnstable
  dependencies:
    - linuxBuildDebugUnstable

# deployment
createJobs:
  stage: deploy
  extends:
    - .createJobsTemplate
  dependencies: []
  variables:
    WinReStableJob: windowsBuildRelease
    WinReUnstableJob: windowsBuildReleaseUnstable
    WinDeStableJob: windowsBuildDebug
    WinDeUnstableJob: windowsBuildDebugUnstable
    LinReStableJob: linuxBuildRelease
    LinReUnstableJob: linuxBuildReleaseUnstable
    LinDeStableJob: linuxBuildDebug
    LinDeUnstableJob: linuxBuildDebugUnstable

triggerJobs:
  stage: deploy
  extends: .only-tags-child
  needs:
    - createJobs
  trigger:
    include:
      - artifact: deploy.yml
        job: createJobs
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate
 
cppcheck:
  stage: codequality
  extends: .cppCheckReportTemplate
  allow_failure: true

pages:
  stage: badges
  extends: .pageTemplate

package:
  stage: package
  extends: .packageTemplate

# badges
badges:
  stage: badges
  extends: 
    - .stable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebug
    - linuxBuildDebug
    - testWin
    - testLinux
    - codingstyle

badgesUnstable:
  stage: badges
  extends: 
    - .unstable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebugUnstable
    - linuxBuildDebugUnstable
    - testWinUnstable
    - testLinuxUnstable
    - codingstyle
