stages:
  - build
  - test
  - codingstyle
  - badges

build:
  stage: build
  script:
    - .\tests\build\build.bat 1>buildLog.txt
  tags:
    - Qt
  artifacts:
    paths:
      - lib/logging/GTlabLogging-d.dll
      - lib/logging/GTlabLogging-d.exp
      - lib/logging/GTlabLogging-d.ilk
      - lib/logging/GTlabLogging-d.lib
      - lib/logging/GTlabLogging-d.pdb
      - build/GTlabUnitTest.exe
      - build/GTlabUnitTest.pdb
      - buildLog.txt
    expire_in: 1 week
nightlyBuild:
  stage: build
  script:
    - .\tests\build\build-nightly.bat
    - .\tests\build\copyHeaders.bat
  tags:
    - Windows7
  artifacts:
    paths:
      - lib/logging/GTlabLogging.dll   
      - lib/logging/GTlabLogging.lib   
      - include/logging/*.h   	  
    expire_in: 1 week
  only:
    - master

build-linux:
  stage: build
  script:
    - ./tests/build/build.sh > linuxBuild.txt 2>&1
  tags:
    - Linux
  artifacts:
    paths:
      - lib/logging/libGTlabLogging-d.so
      - build/GTlabUnitTest
      - linuxBuild.txt
    expire_in: 1 week
nightlyBuild-linux:
  stage: build
  script:
    - ./tests/build/build-nightly.sh
  tags:
    - Linux
  artifacts:
    paths:
      - lib/logging/libGTlabLogging.so    
    expire_in: 1 week	  
  only:
    - master	
# run tests using the binary built before
test:
  stage: test
  script:
    - .\tests\unittests\runUnittests.bat
  tags:
    - Qt
  artifacts:
    paths:
      - "GTlabUnitTestCoverage.xml"
      - "CoverageReport*"
      - "New_Coverage.svg"
      - "unittests.xml"
    expire_in: 1 week
    reports:
      junit: unittests.xml

codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
  tags:
    - Qt
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
    expire_in: 1 week
badges:
  stage: badges
  script:
    - $CommitNumber = git rev-list --count HEAD
    - .\tests\badges\badges.bat --run commits $CommitNumber
    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
    - $filesRaw,$linesRaw = $statistics.split(',')
    - $fileNumber = $filesRaw.split(' ')[1]
    - $linenumber = $linesRaw.split(' ')[1]
    - .\tests\badges\badges.bat --run lines $linenumber
    - .\tests\badges\badges.bat --run files $fileNumber
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
    - .\tests\badges\badges.bat --cs .\codingStyleLog.txt .
  tags:
    - Qt
  artifacts:
    paths:
      - "New_commits.svg"
      - "New_lines.svg"
      - "New_files.svg"
      - "New_BuildWarn-W.svg"
      - "New_CodingStyle.svg"
    expire_in: 1 week
  
