########################################################
###############GTlab Pipeline Version 1.3.0 ############
########################################################

# Environment variables to use in the pipeline globally
variables:
  PROFILENAME: logging.pro
  TARGETDIRNAME: logging
  TARGETNAME: GTlabLogging
  UNITTESTSNAME: GTlabUnitTest
  
  DEVTOOLS_Win: "C:\\devel\\GTlab-DevTools\\stable\\1_6"
  DEVTOOLS_Linux: "/home/gitlab-runner/GTlab-Devtools/stable/1_6"

stages:
  - update
  - build
  - test
  - regressionTest
  - copy
  - codequality
  - badges

devtoolsUpdateWindows:
  stage: update
  script:
    - '& $env:MAINTENANCETOOL --silentUpdate'
  only:
    - master  
  tags:
    - Win10
  variables:
    MAINTENANCETOOL: "C:\\devel\\GTlab-DevTools\\Setup GTlab-DevTools.exe"  

# Windows build
debugBuildWin512:
  stage: build
  script:
    - .\tests\build\build-512.bat 1>buildLog512.txt
  tags:
    - Win10
  artifacts:
    paths:
      - lib\$TARGETDIRNAME\$TARGETNAME-d.dll
      - lib\$TARGETDIRNAME\$TARGETNAME-d.exp
      - lib\$TARGETDIRNAME\$TARGETNAME-d.ilk
      - lib\$TARGETDIRNAME\$TARGETNAME-d.lib
      - lib\$TARGETDIRNAME\$TARGETNAME-d.pdb
      - include\$TARGETDIRNAME\*.h
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog512.txt
    expire_in: 1 week
    when: always  	
  variables:
    BUILDMODE: debug
    BUILDUNITTESTS: "true"
    DEVTOOLS: "$DEVTOOLS_Win"

releaseBuildWin512:
  stage: build
  script:
    - .\tests\build\build-512.bat
  tags:
    - Win10
  only:
    - master
    - tags
  artifacts:
    paths:
      - lib\$TARGETDIRNAME\$TARGETNAME.dll
      - lib\$TARGETDIRNAME\$TARGETNAME.lib
      - include\$TARGETDIRNAME\*.h
    expire_in: 1 week
    when: always 	
  variables:
    BUILDMODE: release
    BUILDUNITTESTS: "false"
    DEVTOOLS: "$DEVTOOLS_Win"

# Linux build
debugBuildLinux512:
  stage: build
  before_script:
    - chmod a+rwx ./tests/build/build-512.sh
  script:
    - ./tests/build/build-512.sh |& tee linuxBuild.txt
  tags:
    - Linux
  artifacts:
    paths:
      - lib/$TARGETDIRNAME/lib$TARGETNAME-d.so
      - include/$TARGETDIRNAME/*.h
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
  variables:
    BUILDMODE: debug
    BUILDUNITTESTS: "true"
    DEVTOOLS: "$DEVTOOLS_Linux"

releaseBuildLinux512:
  stage: build
  before_script:
    - chmod a+rwx ./tests/build/build-512.sh
  script:
    - ./tests/build/build-512.sh
  tags:
    - Linux
  only:
    - master
    - tags
  artifacts:
    paths:
      - lib/$TARGETDIRNAME/lib$TARGETNAME.so*
      - include/$TARGETDIRNAME/*.h
    expire_in: 1 week
  variables:
    BUILDMODE: release
    BUILDUNITTESTS: "false"
    DEVTOOLS: "$DEVTOOLS_Linux"

# run tests using the binary built before
testWin512:
  needs: ["debugBuildWin512"]
  stage: test
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html    
  dependencies:
    - debugBuildWin512
  tags:
    - Win10
  artifacts:
    paths:
      - "unittests.xml"
      - ${UNITTESTSNAME}Coverage.xml
      - CoverageReport* 
    reports:
      junit: unittests.xml
      cobertura: ${UNITTESTSNAME}Coverage.xml  
    expire_in: 1 week
  variables:
    DEVTOOLS: "$DEVTOOLS_Win"

testLinux512:
  needs: ["debugBuildLinux512"]
  stage: test
  before_script:
    - chmod +x ./tests/unittests/runUnittests.sh
  script:
    - ./tests/unittests/runUnittests.sh
  dependencies:
    - debugBuildLinux512
  tags:
    - Linux
  artifacts:
    paths:
      - "unittests.xml"
    expire_in: 1 week
    reports:
      junit: unittests.xml
  variables:
    DEVTOOLS: "$DEVTOOLS_Linux"

# copy files to servers
copyToNightlyBuildWin:
  stage: copy
  script:
    - .\tests\build\copyHeaders-nightlybuild.bat
  dependencies:
    - releaseBuildWin512
  tags:
    - Win10
  only:
    - master
  allow_failure: true
  variables:
    NIGHTLYBUILD: "G:\\AT-TW\\GTlab\\Nightly_Builds_512"

copyForDeploymentWin:
  stage: copy
  script:
    - .\tests\build\copyHeaders-deployment.bat
  dependencies:
    - debugBuildWin512
    - releaseBuildWin512
  tags:
    - Win10
  only:
    - tags
  variables:
    PLATFORMNAME: windows
    BINDIRECTORY: bin\modules
    DEBUGBINDIRECTORY: binDebug\modules

copyForDeploymentLinux:
  stage: copy
  script:
    - .\tests\build\copyHeaders-deployment.bat
  dependencies:
    - debugBuildLinux512
    - releaseBuildLinux512
  tags:
    - Win10
  only:
    - tags
  variables:
    PLATFORMNAME: linux
    BINDIRECTORY: bin\modules
    DEBUGBINDIRECTORY: binDebug\modules

# code quality
codingstyle:
  needs: []
  stage: codequality
  allow_failure: true
  script:
    - '& $env:CODINGSTYLETOOL --ci --output=xml -o .\ -f  .\features\filefilter.txt .\src 1>codingStyleLog.txt'
  tags:
    - Win10
  except:
    - tags
  dependencies:
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt   
    expire_in: 1 week
  variables:
    CODINGSTYLETOOL: "C:\\Program Files\\nsiqcppstyle_0.2.2.3\\nsiqcppstyle\\nsiqcppstyle"
    
cppcheck:
  needs: []
  stage: codequality
  allow_failure: true
  tags:
    - Linux
  before_script:
    - python3 -m venv env
    - source env/bin/activate
    - python3 -m pip install cppcheck-codequality
  script:
    - cppcheck --xml --enable=all src/ 2> cppcheck_out.xml
    - cppcheck-codequality --input-file=cppcheck_out.xml --output-file=codequality.json
  artifacts:
    reports:
      codequality: codequality.json      
      
# badges
badges:
  stage: badges
  script:
    - $CommitNumber = git rev-list --count HEAD
    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
    - $filesRaw,$linesRaw = $statistics.split(',')
    - $fileNumber = $filesRaw.split(' ')[1]
    - $linenumber = $linesRaw.split(' ')[1]
    - '& $env:BADGEGENERATOR --run files $fileNumber'
    - '& $env:BADGEGENERATOR --run commits $CommitNumber'
    - '& $env:BADGEGENERATOR --bw .\buildLog512.txt .'
    - '& $env:BADGEGENERATOR --bw .\linuxBuild.txt .'
    - '& $env:BADGEGENERATOR --cs .\codingStyleLog.txt .'
    - '& $env:BADGEGENERATOR --cc .\${UNITTESTSNAME}Coverage.xml .'
    - '& $env:BADGEGENERATOR --cl .\${UNITTESTSNAME}Coverage.xml .'
  tags:
    - Win10
  except:
    - tags
  artifacts:
    paths:
      - "New_*.svg"
    expire_in: 52 week
  variables:
    BADGEGENERATOR: C:\devel\BadgeBuilder\BadgeGenerator.exe