stages:
  - build
  - test
  - codingstyle
  - badges

build-linux:
  stage: build
  script:
    - ./tests/build/build.sh > linuxBuild.txt 2>&1
  tags:
    - Linux
  artifacts:
    paths:
      - lib/logging/libGTlabLogging-d.so
      - build/GTlabUnitTest
      - linuxBuild.txt
    expire_in: 1 week
    when: always    
  variables:
    DEVTOOLS: "/home/gitlab-runner/gtlab-devtools/"      
nightlyBuild-linux:
  stage: build
  script:
    - ./tests/build/build-nightly.sh
  allow_failure: true      
  tags:
    - Linux
  artifacts:
    paths:
      - lib/logging/libGTlabLogging.so  
      - include/logging/*.h         
    expire_in: 1 week	  
  only:
    - master
  variables:
    DEVTOOLS: "/home/gitlab-runner/gtlab-devtools/"      
buildWindowsQt512:
  stage: build
  script:
    - .\tests\build\buildQt512.bat 1>buildLog.txt
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - lib/logging/GTlabLogging-d.dll
      - lib/logging/GTlabLogging-d.exp
      - lib/logging/GTlabLogging-d.ilk
      - lib/logging/GTlabLogging-d.lib
      - lib/logging/GTlabLogging-d.pdb
      - build/GTlabUnitTest.exe
      - build/GTlabUnitTest.pdb
      - buildLog.txt
    expire_in: 1 week
    when: always  	
  variables:
    DEVTOOLS: "C:\\devel\\GTlab-DevTools\\stable\\1_6"    
nightlyBuildQt512:
  stage: build
  script:
    - .\tests\build\build-nightlyQt512.bat
    - .\tests\build\copyHeaders512.bat
  tags:
    - Win7Qt512
  only:
    - master	
  artifacts:
    paths:
      - lib/logging/GTlabLogging.dll
      - lib/logging/GTlabLogging.lib
      - include/logging/*.h  	  
    expire_in: 1 week
    when: always 		
  variables:
    NIGHTLYBUILD: "G:\\AT-TW\\GTlab\\Nightly_Builds_512"
    DEVTOOLS: "C:\\devel\\GTlab-DevTools\\stable\\1_6"
# run tests using the binary built before

testQt512:
  stage: test
  script:
    - .\tests\unittests\runUnittestsQt512.bat
  tags:
    - Win7Qt512
  dependencies:
    - buildWindowsQt512
  artifacts:
    paths:
      - "unittests.xml"
    expire_in: 1 week
    reports:
      junit: unittests.xml

testLinux:
  stage: test
  script:
    - chmod +x ./tests/unittests/runUnittests.sh
    - ./tests/unittests/runUnittests.sh
  tags:
    - Linux
  dependencies:
    - build-linux
  artifacts:
    paths:
      - "unittests.xml"
    expire_in: 1 week
    reports:
      junit: unittests.xml

codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
    expire_in: 1 week
badges:
  stage: badges
  script:
    - $CommitNumber = git rev-list --count HEAD
    - .\tests\badges\badges.bat --run commits $CommitNumber
    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
    - $filesRaw,$linesRaw = $statistics.split(',')
    - $fileNumber = $filesRaw.split(' ')[1]
    - $linenumber = $linesRaw.split(' ')[1]
    - .\tests\badges\badges.bat --run lines $linenumber
    - .\tests\badges\badges.bat --run files $fileNumber
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
    - .\tests\badges\badges.bat --cs .\codingStyleLog.txt .
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - "New_commits.svg"
      - "New_lines.svg"
      - "New_files.svg"
      - "New_BuildWarn-W.svg"
      - "New_CodingStyle.svg"
      - "New_Coverage.svg"
    expire_in: 52 week
  
